repos:
  - repo: local
    hooks:
      - id: ruff-check-fix
        name: ruff check --fix
        entry: uv run ruff check --fix
        language: system
        types: [python]
        pass_filenames: false

      - id: ruff-format
        name: ruff format
        entry: uv run ruff format
        language: system
        types: [python]
        pass_filenames: false

  - repo: https://github.com/woodruffw/zizmor-pre-commit
    rev: v1.9.0
    hooks:
      - id: zizmor
